#!/bin/bash
#first script

echo "Implementation Assignment 1"
echo "Written by"
echo "Daniel Green"
echo "Grayland Lunn"
echo "and Alex Tovar"
sleep 3s
echo ""
echo "Enhanced divide and conquer runtimes: "
echo "10^2 input vars:"
time python enhanced-divide-and-conquer.py ./Testing\ Cases/random_10_2.txt 
echo ""
echo "10^3 input vars:"
time python enhanced-divide-and-conquer.py ./Testing\ Cases/random_10_3.txt 
echo""
echo "10^4 input vars:"
time python enhanced-divide-and-conquer.py ./Testing\ Cases/random_10_4.txt 
echo ""
echo "10^5 input vars:"
time python enhanced-divide-and-conquer.py ./Testing\ Cases/random_10_5.txt 

echo "Brute force runtimes: "
echo "10^2 input vars:"
time python run-brute-force.py ./Testing\ Cases/random_10_2.txt 
echo ""
echo "10^3 input vars:"
time python run-brute-force.py ./Testing\ Cases/random_10_3.txt 
echo""
echo "10^4 input vars:"
time python run-brute-force.py ./Testing\ Cases/random_10_4.txt 
echo ""
#echo "10^5 input vars:"
#time python enhanced-divide-and-conquer.py ./Testing\ Cases/random_10_5.txt 
